version: '3.8'
services:
  frontend:
    image: rogerortiza/career-path-frontend:latest
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://146.190.125.155:3000
  
  backend:
    image: rogerortiza/career-path-backend:latest
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://altimetrik:SuperSecretPassword@db:5432/career-path

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: career-path
      POSTGRES_PASSWORD: SuperSecretPassword
      POSTGRES_USER: altimetrik
    volumes:
      - ./postgres:/var/lib/postgresql/data
